name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [frontend]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Cache Node.js modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: |
            ${{ matrix.directory }}/node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('${{ matrix.directory }}/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        working-directory: ${{ matrix.directory }}
        run: npm ci --workspaces --prefer-offline --ignore-scripts
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

      - name: Run Lint
        working-directory: ${{ matrix.directory }}
        run: npm run lint

      - name: Run Prettier Check
        working-directory: ${{ matrix.directory }}
        run: npm run prettier:check

      - name: Run Tests
        working-directory: ${{ matrix.directory }}
        run: npm test

      - name: Build Project
        working-directory: ${{ matrix.directory }}
        run: npm run build

      - name: Deploy Project
        if: ${{ matrix.directory == 'frontend' }}
        run: |
          # Add frontend deployment script here
          echo "Deploying frontend..."

      - name: Deploy Backend
        if: ${{ matrix.directory == 'backend' }}
        run: |
          # Add backend deployment script here
          echo "Deploying backend..."
