name: Build and Verify (Non-Main Branches)

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  build-and-verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [frontend, backend]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ${{ matrix.directory }}
        run: npm ci
        continue-on-error: false

      - name: Run Lint
        working-directory: ${{ matrix.directory }}
        run: npm run lint

      - name: Run Prettier Check
        working-directory: ${{ matrix.directory }}
        run: npm run prettier:check

      - name: Run Tests
        working-directory: ${{ matrix.directory }}
        run: npm test

      - name: Build Project
        working-directory: ${{ matrix.directory }}
        run: npm run build
